// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "a945ae7b-a285-42bf-bcf5-db95e86eee07";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onPreassureChange();
void onSetPointChange();
void onLodoChange();
void onPavimentoChange();
void onTierraChange();

float preassure;
int setPoint;
bool lodo;
bool pavimento;
bool tierra;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(preassure, READWRITE, ON_CHANGE, onPreassureChange);
  ArduinoCloud.addProperty(setPoint, READWRITE, ON_CHANGE, onSetPointChange);
  ArduinoCloud.addProperty(lodo, READWRITE, ON_CHANGE, onLodoChange);
  ArduinoCloud.addProperty(pavimento, READWRITE, ON_CHANGE, onPavimentoChange);
  ArduinoCloud.addProperty(tierra, READWRITE, ON_CHANGE, onTierraChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
